FROM nginx:alpine AS hr-web

# Copy nginx configuration file
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy build files to nginx
RUN rm -rf /usr/share/nginx/html/*
COPY /dist/apps/check-me-web/browser /usr/share/nginx/html

# give permission to nginx user
RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

USER nginx

# Expose port 3000
EXPOSE 3000

# Start nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
